name: linter
version: 0.2.0-nullsafety.0

description: >-
  The implementation of the lint rules supported by the analyzer framework.
  This package is not intended to be used directly.
homepage: https://github.com/dart-lang/linter
repository: https://github.com/dart-lang/linter
documentation: https://dart-lang.github.io/linter/lints

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies:
  analyzer: ^0.41.1
#  args: ^2.0.0-nullsafety.0
  args: ^1.0.0
  charcode: ^1.0.0
  # todo: update grinder
#  glob: ^2.0.0-nullsafety.0
  glob: ^1.0.3
  http: ^0.12.0
  meta: ^1.3.0-nullsafety
  path: ^1.8.0-nullsafety
  source_span: ^1.8.0-nullsafety.4
  yaml: ^3.0.0-nullsafety.0

dev_dependencies:
  async: any # referenced in tests
  benchmark_harness: ^2.0.0-nullsafety
#  cli_util: ^0.3.0-nullsafety
  cli_util: '>=0.1.4 <0.3.0'
  fixnum:
    path: test/mock_packages/fixnum
  github: '>=6.0.5 <8.0.0'
  grinder: ^0.8.0
  markdown: '>=2.0.0 <4.0.0'
  matcher: ^0.12.10-nullsafety
  pedantic: ^1.10.0-nullsafety
#  pub_semver: ^2.0.0-nullsafety
  pub_semver: ^1.4.2
  test: ^1.16.0-nullsafety

# todo: not for publishing (obviously)
dependency_overrides:
  _fe_analyzer_shared:
    path: ../dart/sdk/pkg/_fe_analyzer_shared
  analyzer:
    path: ../dart/sdk/pkg/analyzer

